import type { KnowledgeCard } from "../types";

export const KNOWLEDGE_CARDS: KnowledgeCard[] = [
  {
    slug: "what-is-an-origin",
    question: "What is an origin?",
    definition: "The actual server or infrastructure running your application, sitting behind Cloudflare's reverse proxy.",
    whyItMatters: "Almost every troubleshooting question ('why is this slow', 'why did this 5xx happen') eventually comes down to: is this a Cloudflare-edge problem or an origin problem? You can't reason about the architecture without a clear mental model of what the origin is.",
    example: "An EC2 instance, an AKS cluster, an on-prem web server, or a Workers deployment (which can itself be the 'origin' for other requests).",
    architecture: "Browser -> Cloudflare Edge -> Origin",
    misconception: "That 'origin' means 'the origin's DNS record' — it means the actual compute serving the response, which may be reached via any number of DNS records.",
  },
  {
    slug: "what-is-a-reverse-proxy",
    question: "What is a reverse proxy?",
    definition: "A server-side intermediary that terminates the client's connection and makes its own separate connection to the origin, transparent to the client.",
    whyItMatters: "It explains why origin logs show Cloudflare's IP by default, why TLS has two independent legs, and why the origin can be hidden from direct discovery via DNS.",
    example: "Cloudflare, nginx as a reverse proxy, an AWS ALB — all share this pattern, just at different scopes.",
    architecture: "Browser <-> Reverse Proxy <-> Origin (two connections, not one)",
    misconception: "Confusing a reverse proxy with a forward proxy (which proxies outbound client requests to arbitrary destinations, e.g. a corporate web filter) — they solve opposite problems.",
  },
  {
    slug: "what-does-orange-cloud-mean",
    question: "What does orange-cloud mean?",
    definition: "The Cloudflare dashboard indicator that a DNS record is Proxied — traffic for that hostname is routed through Cloudflare's edge rather than resolved to the origin's real IP directly.",
    whyItMatters: "It's the single toggle that determines whether WAF, CDN, Bot Management, and DDoS protection apply to a hostname at all.",
    example: "www proxied (orange), ftp DNS-only (grey), in the same zone.",
    misconception: "That orange-cloud alone fully hides or secures the origin — it reduces exposure but doesn't guarantee the IP can never be discovered.",
  },
  {
    slug: "what-is-an-authoritative-dns-server",
    question: "What is an authoritative DNS server?",
    definition: "The DNS server that is the actual source of truth for a zone's records — as opposed to a recursive resolver, which caches and forwards queries on a client's behalf.",
    whyItMatters: "Distinguishes 'what Cloudflare is actually serving right now' (query the authoritative nameservers directly) from 'what a given resolver has cached' (which may be stale).",
    example: "Querying dig @<name>.ns.cloudflare.com example.com bypasses caching entirely and shows the current authoritative answer.",
    misconception: "That all DNS servers are equivalent — a recursive resolver's cached answer can lag behind what's authoritative.",
  },
  {
    slug: "what-is-a-waf",
    question: "What is a WAF?",
    definition: "Web Application Firewall — inspects HTTP(S) requests for proxied hostnames and blocks, challenges, or logs traffic matching Managed or Custom Rules.",
    whyItMatters: "It's the primary L7 security control, but only for proxied traffic — a common source of 'why wasn't this blocked' confusion when a record is DNS-only.",
    example: "Blocking a request whose query string matches a known SQL injection pattern.",
    architecture: "Browser -> TLS -> WAF -> Rate Limiting -> Bot Management -> Cache -> Origin",
    misconception: "That a WAF understands application business logic — it inspects request structure/content against rules, not your app's authorization decisions.",
  },
  {
    slug: "what-is-a-managed-rule",
    question: "What is a managed rule?",
    definition: "A vendor-maintained (Cloudflare-authored) WAF rule detecting a known attack signature, updated as new threats are discovered.",
    whyItMatters: "Gives broad protection with no rule-writing required, but is generic — it doesn't know your specific business logic.",
    example: "The Cloudflare Managed Ruleset's SQL injection detection group.",
    misconception: "That enabling Managed Rules means you never need Custom Rules — they solve different problems (known attacks vs. your own policy).",
  },
  {
    slug: "what-is-a-custom-rule",
    question: "What is a custom rule?",
    definition: "An organization-defined WAF rule using Cloudflare's expression language to enforce business-specific policy.",
    whyItMatters: "It's how you encode access policy (geo-blocking an admin path, allowlisting a monitor) that no generic rule could know.",
    example: "http.request.uri.path eq \"/admin\" and not ip.src in {203.0.113.5}",
    misconception: "That Custom Rules are only for blocking — Skip, Log, and Challenge actions are equally common and important.",
  },
  {
    slug: "what-is-a-bot-score",
    question: "What is a bot score?",
    definition: "A 1-99 score estimating how likely a request came from an automated client, derived from fingerprinting, behavior, and reputation signals.",
    whyItMatters: "Lets you make graduated decisions (allow / challenge / block) instead of a binary human-or-not judgment based on a single weak signal like User-Agent.",
    example: "A scripted, sequential scraper might score 1-10; a real browser with normal navigation patterns typically scores much higher.",
    misconception: "That a low score always means malicious — some low-scoring traffic is a wanted bot (a partner integration) that should be allowlisted, not blocked.",
  },
  {
    slug: "what-is-a-cache-hit",
    question: "What is a cache hit?",
    definition: "A response served directly from Cloudflare's edge without contacting the origin, because a valid cached copy already existed for that cache key.",
    whyItMatters: "Cache hit ratio is one of the clearest levers for both performance and origin load reduction.",
    example: "cf-cache-status: HIT on a static asset request.",
    misconception: "That HTML pages are cached by default the same way static assets are — most configurations require an explicit Cache Rule for HTML.",
  },
  {
    slug: "what-is-tls-termination",
    question: "What is TLS termination?",
    definition: "The point in the request path where an encrypted TLS connection is decrypted. For proxied Cloudflare traffic, the browser-facing leg terminates at the edge.",
    whyItMatters: "It's why the SSL/TLS mode setting (Flexible/Full/Full Strict) matters — it controls whether the second leg, edge-to-origin, is also encrypted and validated.",
    example: "In Full (Strict) mode, TLS is terminated and re-established twice: once at the edge, once (validated) at the origin.",
    misconception: "That 'HTTPS is enabled' means the entire path end-to-end is encrypted with equal rigor — Flexible mode explicitly is not.",
  },
  {
    slug: "what-is-cloudflare-tunnel",
    question: "What is Cloudflare Tunnel?",
    definition: "A connector (cloudflared) that establishes outbound-only connections from an origin network to Cloudflare, removing the need for any inbound-open port.",
    whyItMatters: "Fundamentally different attack-surface reduction than firewalling a public IP — there's no inbound listener to discover at all.",
    example: "An internal app reachable only via a Tunnel hostname, gated by Access, with zero inbound firewall rules.",
    misconception: "That Tunnel alone provides authentication — it removes exposure; Access provides the identity policy layer on top.",
  },
  {
    slug: "what-causes-522",
    question: "What causes a 522 error?",
    definition: "Connection Timed Out — Cloudflare could not establish a TCP connection to the origin within the timeout window.",
    whyItMatters: "It's one of the most common production incidents and almost always points to origin availability or firewall/network path issues, not Cloudflare itself.",
    example: "Origin server crashed, or its firewall stopped allowing Cloudflare's IP ranges after a security tooling change.",
    misconception: "That a 522 means Cloudflare is down — it specifically means Cloudflare couldn't reach the origin, the opposite implication.",
  },
];
